/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tquthdydnddzfwdnnyci"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdXRoZHlkbmRkemZ3ZG5ueWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwODI5MzEsImV4cCI6MjA4ODY1ODkzMX0.p0fyo24oRVF7bgyZ_c-LvNLOtHZ4csWu0Jffuga4N-U"